### ISSUE TITLE
Door locks

### ISSUE THREAD

**Issue by dollar-src** [renzuzu/renzu_motels#1]
some how  locks are  doesnt work for me
when ```Config.Mlo = true```
shared_script '@renzu_shield/init.lua'
and renzu_shiled missing

**Comment by renzuzu** [comment]
thank you for reporting this.
this commit probably will fix that issue. (as i havent able to test a MLO yet)

and latest commits breaks the new old formats of savings

**Comment by dollar-src** [comment]
thx !   i ll wait for update

**Comment by renzuzu** [comment]
i already tested, i forgot i remove the doorhash from config, thats why its not working, thank you

**Comment by dollar-src** [comment]
problem solved thanks again

**Comment by renzuzu** [comment]
the last update i mention in my last comment was still broke (zone type) targets is no issue
