### ISSUE TITLE
Missing images/icons

### ISSUE THREAD

**Issue by jellyton69** [renzuzu/renzu_motels#11]
![FiveM_b2802_GTAProcess - March25 - 19 59 - 1872](https://user-images.githubusercontent.com/20498875/227752828-c4a25927-8d9c-434c-b492-ad3595a9f154.png)
![FiveM_b2802_GTAProcess - March25 - 19 59 - 1871](https://user-images.githubusercontent.com/20498875/227752830-0cc37415-52eb-4aaa-949a-a51175f36a36.png)

**Comment by Kevlo1997** [comment]
Same Issue.

**Comment by renzuzu** [comment]
pinkcage is the only complete sample provided here.

but if its necessary to have a 3 pre configured motels i will do it :D

**Comment by renzuzu** [comment]
closing, as the resource pre configured is only Pink cage.

ill trry pushing more preconfigured when i have a a time to do it.
