### ISSUE TITLE
Script Error for Latest ESX Legacy

### ISSUE THREAD

**Issue by Kevlo1997** [renzuzu/renzu_motels#12]
SCRIPT ERROR: @renzu_motels-main/server/main.lua:161: attempt to index a nil value (local 'toPlayer')

Also, doors after paying the hotel rent isnt appearing.

**Comment by renzuzu** [comment]
i fixed regarding error when you put a non existent playr.

>Also, doors after paying the hotel rent isnt appearing.

need more informtion
