### ISSUE TITLE
Door Lock

### ISSUE THREAD

**Issue by maalouane** [renzuzu/renzu_motels#13]
I got a motel mlo and the door locks are the left side, but the script has a predefined location for all locks on the right, is there any way to change it?

**Comment by renzuzu** [comment]
in config? you can change all the coordinates

the default config is preconfigured to gabz pinkcage.

**Comment by maalouane** [comment]
I am talking about the door lock, not the door itself, trying to find the config for the door lock target coords but could not find them

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/227886723-dcf0909a-6ca3-4d7a-9655-087f67ae8543.png)

this is the door lock coordinates
