### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Brito1227** [renzuzu/renzu_motels#14]
![image](https://user-images.githubusercontent.com/104800808/227798488-ec37075e-8a51-435a-9d70-0b8fdce46024.png)

 I'm having this error when trying to buy the motel always giving error

**Comment by renzuzu** [comment]
do you have money in pocket?
check if theres an error from server.

this part only checks money from pocket / inventory
it will return false if you dont have enough

**Comment by Brito1227** [comment]
> do you have money in pocket? check if theres an error from server.
> 
> this part only checks money from pocket / inventory it will return false if you dont have enough

the problem here is that I use money as an item and it does not verify that money, is it not possible to change it to money in the bank?
