### ISSUE TITLE
SCRIPT ERROR: @renzu_motels/client/main.lua:744: attempt to call a nil value (global 'MotelFunction')

### ISSUE THREAD

**Issue by mrdigital0** [renzuzu/renzu_motels#15]
SCRIPT ERROR: @renzu_motels/client/main.lua:744: attempt to call a nil value (global 'MotelFunction')

**Comment by renzuzu** [comment]
if you dont have ox_target or qb-target
set the config.target to false

**Comment by renzuzu** [comment]
> i figured out the issue but i have another issue when you try to goto the door you get a error for it to grab inventoryitemssays its nil

need more information
