### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by YungT-SevsideRP** [renzuzu/renzu_motels#31]
if i put mlo = true will the vectors put for the gabz motel mlo?

**Comment by renzuzu** [comment]
its should work the pink cage is setup in gabz MLO (the paid one)
i dont know if the leaks is the same coordinats

**Comment by YungT-SevsideRP** [comment]
> its should work the pink cage is setup in gabz MLO (the paid one) i dont know if the leaks is the same coordinats

ye I have the gabz silver pack so ye, but thx I realised after I read you said it works with the gabz mlo so I just closed it
