### ISSUE TITLE
Qb Inventory

### ISSUE THREAD

**Issue by SantyR0** [renzuzu/renzu_motels#39]
How do I make it work with qb-inventory or lj-inventory? 
I'm receiving this error.

cl/main.lua:135 attempt to call a nil value (global ‘open stash’)

**Comment by renzuzu** [comment]
show me the whole error

**Comment by renzuzu** [comment]
Are you using lj inv?

**Comment by renzuzu** [comment]
> Are you using lj inv?

Just replace inventory files to 
Rename the exports

**Comment by SantyR0** [comment]
Thanks
