### ISSUE TITLE
Can't Get it To Work

### ISSUE THREAD

**Issue by dejadabber** [renzuzu/renzu_motels#45]
i cant get it to work period

**Comment by dejadabber** [comment]
How you gonna close as complete when you never helped. This was gonna determine rather i bought a script or notSent from my iPhoneOn Apr 16, 2023, at 3:38 AM, renzuzu ***@***.***> wrote:﻿
Closed #45 as completed.

**Comment by renzuzu** [comment]
when opening a ticket you should provide minimal information.

>This was gonna determine rather i bought a script

what you mean by this? this is free resource
