### ISSUE TITLE
Doors with "Unknown" hash names

### ISSUE THREAD

**Issue by Kingsman40** [renzuzu/renzu_motels#5]
trying to create a motel at the Davis Motel which I have an MLO for. But when I use the Free Aim Mode in the Entity Viewer in qbcore /admin to view the entity, the doors have "Unknown" hash names. Can you make it so it can also use the hash number if a hash name is not known?

 For example, Door 1 of the Davis Motel hash number is -1753326354. Each door has a different one. Or some other way to be able to use any door even if the name is unknown?

**Comment by renzuzu** [comment]
most of MLO cannot be detect with some dev tools.

you need to open OPENIV and check the door names

you can also put

door = -1753326354.

**Comment by Kingsman40** [comment]
I tried:
door = -1753326354
It didn't work.

But after doing what you suggested and getting the hash from openiv, it worked.

To test it, I rented a room and received the key, but can't seem to unlock the door. And target is set in config.target = true, but qb-target doesn't seem to do anything.

**Comment by renzuzu** [comment]
what it didnt work can you elaborate?

>door = -1753326354

if this is your issue.
probably the hash is incorrect

**Comment by Kingsman40** [comment]
Not work, meaning it didn't lock the door and I was able to go in and out freely.

No worries though, it worked when I got the hash name from openiv.

**Comment by renzuzu** [comment]
yes its more reliable to get the door name of model from OPENIV.
