### ISSUE TITLE
error after download new version

### ISSUE THREAD

**Issue by LukasPovilaitis** [renzuzu/renzu_motels#50]
Hello, after downloaded new version of renzu motels, I got this error: 
![image](https://user-images.githubusercontent.com/106585396/234036543-3bf2d08f-221a-4244-b3df-666e2cc2d630.png)

**Comment by renzuzu** [comment]
update the config too

**Comment by renzuzu** [comment]
theres a major refactor in the client side and config

**Comment by LukasPovilaitis** [comment]
oh, sorry then, my bad.

**Comment by renzuzu** [comment]
no worries the latest version is beta (main branch not the release download)
the update is to support MLO's with multiple door hashes

**Comment by LukasPovilaitis** [comment]
solved
