### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by dollar-src** [renzuzu/renzu_motels#6]
When the motel time is up, the players stay inside. What can be done about it?

**Comment by renzuzu** [comment]
do you want to owner should manually kick players?

**Comment by Kingsman40** [comment]
My suggestion would be to have an auto-kick from room and give owner option to evict from room.

**Comment by renzuzu** [comment]
>My suggestion would be to have an auto-kick from room and give owner option to evict from room.

do you mean they wont have access to door until they renew the rent?

**Comment by Kingsman40** [comment]
> do you mean they wont have access to door until they renew the rent?

Give the owner the option to kick the player out of the room. For example, if a player doesn't pay the balance due, the owner can do command, something like  /motel-evict (player id). 

Or, if a player is outside of the room and they have not paid the balance due, then the next time the player enters the room, they will get kicked out from it and the door will lock and no longer be accessible with their key. A notification will show for the player they have an outstanding balance and if they want access to the room, they will need to pay the balance.

**Comment by renzuzu** [comment]
>And to make it easier to find the players ID, maybe have a room rental screen that shows which player is renting the room with name and ID.

this is already a thing when you owned the motel
go to Room list or Occupant List
and check the Rooms and you can see the list of occupants.
you dont need either a command to kick there is a Kick function when you click on the player room slot.

>Give the owner the option to kick the player out of the room. For example, if a player doesn't pay the balance due, the owner can do command, something like /evict (player id).

Or, if a player is outside of the room and they have not paid the balance due, then the next time the player enters the room, they will get kicked out from it and the door will lock and no longer be accessible with their key. A notification will show for the player they have an outstanding balance and if they want access to the room, they will need to pay the balance.

i will try to add this

**Comment by Kingsman40** [comment]
> this is already a thing when you owned the motel
> go to Room list or Occupant List
> and check the Rooms and you can see the list of occupants.
> you dont need either a command to kick there is a Kick function when you click on the player room slot.

Ah okay, sorry. I am building my server and testing things by myself, so I did not see the option. Thank you for letting me know.



> i will try to add this

Great! I think it will be a great feature to have.
