### ISSUE TITLE
index a nil value on Start Up

### ISSUE THREAD

**Issue by r0uzy** [renzuzu/renzu_motels#71]
`[ script:renzu_motels] SCRIPT ERROR: @renzu_motels/server/main.lua:30: attempt to index a nil value (field '?')
[ script:renzu_motels] > <unknown> (@oxmysql/dist/build.js:22252)
[ script:renzu_motels] > runMicrotasks (<anonymous>:0)
[ script:renzu_motels] > processTicksAndRejections (node:internal/process/task_queues:96)`

**Comment by Brave-developments** [comment]
What was the fix?
