### ISSUE TITLE
ox_target

### ISSUE THREAD

**Issue by atrektor** [renzuzu/renzu_motels#9]
For some reason doesn't matter what values i set here the target does not work it brings only markers all the time.
![image](https://user-images.githubusercontent.com/125280352/227748662-7fcf2a05-951d-4319-a6f2-d8a2b910d0a4.png)

**Comment by renzuzu** [comment]
are you talking about rental marker?
this is fixed marker.

let me if this is the issue i can make an adjustment

**Comment by atrektor** [comment]
i got it no worries, by any chance can you advise where i can change the radius for targets and labels? 
Since I can target the stash outside of the room (MLO).

**Comment by atrektor** [comment]
I see labels for the target are the actual data type, it will be not so easy to translate everything :D

**Comment by renzuzu** [comment]
> I see labels for the target are the actual data type, it will be not so easy to translate everything :D

i will see what i can do on this..
thank for notifying me
